# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Dong-Kyu Chae
tagline:          'homepage'
description:      I am a postdoctoral researcher at <a href="https://cc.gatech.edu/" target="_blank">Georgia Tech</a> working with <a href="https://poloclub.github.io/polochau/" target="_blank">Prof. Polo</a>'s <a href="https://poloclub.github.io/" target="_blank">data science group</a>.
url:              'https://dkchae.github.io/'
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Dong-Kyu Chae'
  url:            https://dkchae.github.io/

paginate:         1
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

google_analytics: UA-153070260-1
